### ISSUE TITLE
[BUG] Python Apps on V4 suddenly getting import errors

### ISSUE THREAD

**Issue by stewrutledge** [Azure/azure-functions-python-worker#1088]
Not sure where this issue belongs, posted the same in https://github.com/Azure/azure-functions-python-worker/issues/1091

Investigative information

Please provide the following:

    Timestamp: 2022-08-19T09:31:17.043Z
    Function App version: 4
    Invocation ID: 293176d4-510c-4237-b289-7facf2b18af2
    Region: West Europe

Repro steps

Create a function app using python and runtime version 4 and set FUNCTIONS_WORKER_PROCESS_COUNT to 5.

4 out of 5 instances of the function app will get ModuleNotFoundError, 1 out of 5 will work correctly.
Expected behavior

No exceptions
Actual behavior

Function suddenly getting ModuleNotFoundError after months, with 0 changes to function app. Fails on the first non-standard library module included in the imports.
Known workarounds

Setting FUNCTIONS_WORKER_PROCESS_COUNT to 1 and reducing to one instance.
Related information

Python 3.8.

**Comment by kkrellwitz** [comment]
We have just started seeing this issue this morning.  If I set FUNCTIONS_WORKER_PROCESS_COUNT to anything above 1, I get the requests ModuleNotFoundError exception.   The functions have been running fine for over a year until today.

The function is using the consumption plan on linux.

**Comment by Leonidas-MOH** [comment]
My function needs to warm up
Try to execute manually -> import error pandas
1 Second later
Try again -> import error pandas
1 Second later
Try again -> Function Executed OK connected to SQL send mail process pandas and returns a 200
1 Second later
Try again -> import error pandas

The deterministic function execution is a joke in Seattle,
Ok, it is a consumption plan but the storage of the SQL and all the others are not,
This problem started on at 17/8/2022 about 10:00 CET and is not fixed till now.

**Comment by stewrutledge** [comment]
We are building packages locally:

`pip install  --target=".python_packages/lib/site-packages"  -r requirements.txt`

Then deploying with `--no-build`

@kkrellwitz or @Leonidas-MOH are you building locally or remotely?

**Comment by Leonidas-MOH** [comment]
Hello

I do publish with --build remote

I have set FUNCTIONS_WORKER_PROCESS_COUNT to 1 and this seems to work.I will wait till the app gets in a really busy state to confirm if it is OK.

I will try the solution you mention later on.
This will upload the libs source to ".python_packages/lib/site-packages" to prevent the build process to fetch them again;


Καπασακάλης Λεωνίδας

IT Department

[MotorOil_logo_200-60]

Ηρώδου Αττικού 12Α

151 24 Μαρούσι, Αττική

Τηλ: +302108093570

Κινητό:+306979111998

Email: ***@***.*** -

________________________________
Από: stewrutledge ***@***.***>
Στάλθηκε: Δευτέρα, 22 Αυγούστου 2022 9:56 πμ
Προς: Azure/azure-functions-python-worker ***@***.***>
Κοιν.: Kapassakalis Leonidas ***@***.***>; Mention ***@***.***>
Θέμα: Re: [Azure/azure-functions-python-worker] [BUG] Python Apps on V4 suddenly getting import errors (Issue #1088)


We are building packages locally:

pip install --target=".python_packages/lib/site-packages" -r requirements.txt

Then deploying with --no-build

@kkrellwitz<https://github.com/kkrellwitz> or @Leonidas-MOH<https://github.com/Leonidas-MOH> are you building locally or remotely?

**Comment by stewrutledge** [comment]
I found this commit:

https://github.com/Azure/azure-functions-python-worker/commit/b1085b5bbba2b4e71043f1de3d3bbfab9efa0d0b

Related to a preview feature. It seems like the new default conflicts with the documentation:

[PYTHON_ISOLATE_WORKER_DEPENDENCIES_DEFAULT](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#python_isolate_worker_dependencies-preview)

Which states that it is disabled by default

When I changed this to 0, I am now having the opposite problem: 1/5 fails and 4/5 execute correctly.

**Comment by kkrellwitz** [comment]
@stewrutledge We use Azure DevOps pipeline to do the build and deploy.  The function has been running fine for about a year without issue.  Recently we upgraded it to the v4 runtime, maybe a month or two ago, and it has been working fine until Saturday morning.  After changing the FUNCTIONS_WORKER_PROCESS_COUNT to 1 it works fine, but there was a performance hit setting it to 1.   Our other functions that are still using v3 of the runtime do not have this issue.

**Comment by stewrutledge** [comment]
@kkrellwitz If you change `PYTHON_ISOLATE_WORKER_DEPENDENCIES` to 0 on the app, do you get the "opposite" problem? That is, only 1 out of n fails?

**Comment by Leonidas-MOH** [comment]
Hello

Thank you for your answer i appreciate it a lot.

My function started as v4 and is running fine for about 3 month till the day you mention.
I dont think than i will downgrade it to v3 because ms is unable to set up a working enviroment (v4 is not beta and the consumption plan is still available and receiving revenues)
I have set FUNCTIONS_WORKER_PROCESS_COUNT to value higher than 1 after a v3 function giving timeouts without any real code execution in a random manner. and investigateting with ms for a  period of 2 moths,

Thank yoy again,




Καπασακάλης Λεωνίδας

IT Department

[MotorOil_logo_200-60]

Ηρώδου Αττικού 12Α

151 24 Μαρούσι, Αττική

Τηλ: +302108093570

Κινητό:+306979111998

Email: ***@***.*** -

________________________________
Από: Keith Krellwitz ***@***.***>
Στάλθηκε: Δευτέρα, 22 Αυγούστου 2022 3:32 μμ
Προς: Azure/azure-functions-python-worker ***@***.***>
Κοιν.: Kapassakalis Leonidas ***@***.***>; Mention ***@***.***>
Θέμα: Re: [Azure/azure-functions-python-worker] [BUG] Python Apps on V4 suddenly getting import errors (Issue #1088)


@stewrutledge<https://github.com/stewrutledge> We use Azure DevOps pipeline to do the build and deploy. The function has been running fine for about a year without issue. Recently we upgraded it to the v4 runtime, maybe a month or two ago, and it has been working fine until Saturday morning. After changing the FUNCTIONS_WORKER_PROCESS_COUNT to 1 it works fine, but there was a performance hit setting it to 1. Our other functions that are still using v3 of the runtime do not have this issue.

**Comment by JoseTrigueiro** [comment]
Currently and since Wednesday, I've been experiencing a similar issue to @kkrellwitz, also deploying from Azure DevOps. In my case, it is the azure-durable-function module that is not found by the worker, setting FUNCTIONS_WORKER_PROCESS_COUNT to 1 seems to be a temporary fix to the issue.

**Comment by Leonidas-MOH** [comment]
Hello

The problem i have is not running the function in every execution with random 500 import error occurrences.(after manually executing the function in the second third try the function recovers from the zombie state and all imports are found, if you try once more you are in the same chaotic state)

I notify this after 1 day of the function failure.
Due to the app scope, I have same trigger function that triggers the main execution function that do the work.
At this time I have not found any problems with the FUNCTIONS_WORKER_PROCESS_COUNT  = 1 and  I am going to check the PYTHON_ISOLATE_WORKER_DEPENDENCIES today.

When I try it I will notify.


Καπασακάλης Λεωνίδας

IT Department

[MotorOil_logo_200-60]

Ηρώδου Αττικού 12Α

151 24 Μαρούσι, Αττική

Τηλ: +302108093570

Κινητό:+306979111998

Email: ***@***.*** -

________________________________
Από: stewrutledge ***@***.***>
Στάλθηκε: Δευτέρα, 22 Αυγούστου 2022 3:37 μμ
Προς: Azure/azure-functions-python-worker ***@***.***>
Κοιν.: Kapassakalis Leonidas ***@***.***>; Mention ***@***.***>
Θέμα: Re: [Azure/azure-functions-python-worker] [BUG] Python Apps on V4 suddenly getting import errors (Issue #1088)


@kkrellwitz<https://github.com/kkrellwitz> If you change PYTHON_ISOLATE_WORKER_DEPENDENCIES to 0 on the app, do you get the "opposite" problem? That is, only 1 out of n fails?

**Comment by Leonidas-MOH** [comment]
The same with me.
Beware for lost runs due to timeout if you are in a consumption plan


Καπασακάλης Λεωνίδας

IT Department

[MotorOil_logo_200-60]

Ηρώδου Αττικού 12Α

151 24 Μαρούσι, Αττική

Τηλ: +302108093570

Κινητό:+306979111998

Email: ***@***.*** -

________________________________
Από: JoseTrigueiro ***@***.***>
Στάλθηκε: Δευτέρα, 22 Αυγούστου 2022 5:10 μμ
Προς: Azure/azure-functions-python-worker ***@***.***>
Κοιν.: Kapassakalis Leonidas ***@***.***>; Mention ***@***.***>
Θέμα: Re: [Azure/azure-functions-python-worker] [BUG] Python Apps on V4 suddenly getting import errors (Issue #1088)


Currently and since Wednesday, I've been experiencing a similar issue to @kkrellwitz<https://github.com/kkrellwitz>, also deploying from Azure DevOps. In my case, it is the azure-durable-function module that is not found by the worker, setting FUNCTIONS_WORKER_PROCESS_COUNT to 1 seems to be a temporary fix to the issue.

**Comment by tbock** [comment]
Same started occurring on our function ~2 days ago.  Switching to runtime version ~3 resolved the issue.

**Comment by Leonidas-MOH** [comment]
I tried the PYTHON_ISOLATE_WORKER_DEPENDENCIES 0,1 and all the results are 500 
I removed it and it started working OK
I think the only solution is setting  FUNCTIONS_WORKER_PROCESS_COUNT = 1 with the penalty of missed executions

**Comment by souvikg10** [comment]
Hello,
We have been facing the same issue and i have tried several different workaround and so far none of them has worked. We use the Function App Consumption Plan

Here are a few things we tried so far..
1. Using LinuxFx Image: Python3.7, added Function worker process count to 1 and isolate worker dependencies to 0, all results to error 500.
2. We tried the following workaround listed here: https://docs.microsoft.com/en-us/answers/questions/976311/modulenotfounderror-on-external-packages.html. I tried exactly that but i started receiving error 503, my best guess is because Linux Fx image is not recognized. I tried several of the images and all resulted in the same error. Error 503.
3. We tried different combinations of the above two and none of them seemed to have worked for us so far. 

I understand there is an open MR, that is suppose to resolve this issue but in the meantime, if there are other workaround i could try, please let me know. 

Thanks for the help.

**Comment by Leonidas-MOH** [comment]
> 

Hello

The only working solution working for me in a consumption plan is 
FUNCTIONS_WORKER_PROCESS_COUNT = 1
NOT PYTHON_ISOLATE_WORKER_DEPENDENCIES in config

**Comment by souvikg10** [comment]
I tried that as well. It shows error 500 😢

**Comment by Leonidas-MOH** [comment]
> I tried that as well. It shows error 500 😢 Could you share the version of Azure functions you are using? Also the python image. I will try to replicate that

Azure Function 4
Python 3.8
When in used the DOCKER|azure-functions/python:4.8.0-python3.8 the oryx build use Python 3.6 and I end up with a not working function at all

**Comment by souvikg10** [comment]
same here. we used Azure Function 4, python 3.8, the image for Docker didn't work for us either.

**Comment by Leonidas-MOH** [comment]
I used the following for the working one
    "name": "BUILD_FLAGS",    "value": "UseExpressBuild",
    "name": "ENABLE_ORYX_BUILD",    "value": "true",
    "name": "FUNCTIONS_EXTENSION_VERSION",    "value": "~4",
    "name": "FUNCTIONS_WORKER_PROCESS_COUNT",    "value": "1",
    "name": "FUNCTIONS_WORKER_RUNTIME",    "value": "python",
    "name": "PYTHON_THREADPOOL_THREAD_COUNT",    "value": "6",
    "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",    "value": "1",
and publish --build remote

**Comment by gavin-aguiar** [comment]
The fix for this issue is being rolled out with runtime version 4.10.2.
For a mitigation, try and set the flag PYTHON_ISOLATE_WORKER_DEPENDENCIES to 0.

**Comment by Takadonet** [comment]
> The fix for this issue is being rolled out with runtime version 4.10.2.
> For a mitigation, try and set the flag PYTHON_ISOLATE_WORKER_DEPENDENCIES to 0.

Any timeline provided or update feed to follow?

**Comment by Leonidas-MOH** [comment]
I just checked it and works fine. (With FUNCTIONS_WORKER_PROCESS_COUNT > 1)

**Comment by kkrellwitz** [comment]
Looks like they rolled the runtime back to 4.8.0.0, at least in my environment.

**Comment by vrdmr** [comment]
Hi All, We identified an issue with the dependency isolation feature, which caused the issue here. We have rolled it back to 4.8.4 and rolled the new 4.10.4 release with the feature disabled.

I sincerely apologize that you had to face this issue. The fix was done to prevent the Protobuf rollout (major version change causing the apps depending on protobuf not running) and this was an unintended consequence of this issue.

**Comment by waltherg** [comment]
I've been getting this behaviour for about a week or so on V4 on a consumption plan and runtime version `4.14.0.0`.
I had already set `PYTHON_ISOLATE_WORKER_DEPENDENCIES = 1` after lengthy debugging sessions weeks / months ago to take care of some protobuf issue. Now this.

Really frustrated by the sudden and intransparent failure modes of Azure functions that tend to be hard and time-consuming to debug.
