### ISSUE TITLE
Visual Studio Code Azure Functions Python Multi-root project import shared code 

### ISSUE THREAD

**Issue by JeroenMBooij** [Azure/azure-functions-python-worker#1144]
In my workspace I have two azure function projects, one for durable functions and one for regular functions

```
Workspace
|_ durable_functions
     |_ hello
         |_ __init__.py
         | function.json
     |_ hello_http_start
         |_ __init__.py
         | function.json
     |_ hello_orchestrator
         |_ __init__.py
         | function.json

|_ functions
     |_ hello
         |_ __init__.py
         | function.json
     |_ script
         |_ __init__.py
         | function.json

|_ shared
     |_ my_pack_one
         |_ __init__.py
         | class_one.py
     |_ my_pack_two
         |_ __init__.py
         | class_two.py

```

How do I import the shared modules into my functions and into my durable functions?

if I try a relative import I get a `Exception: ValueError: attempted relative import beyond top-level package`

`from ....workspace.shared.my_pack_one.class_one import ClassOne`

**Comment by kummerer94** [comment]
From what I know, only the folder above the functions is deployed. That means if you deploy your `durable_functions` project, just the `durable_functions` folder is deployed. That is why you cannot import something from the `Workspace` folder. (Might also have to do with the way the package discovery works in connection to the python runner.)

I suggest something else from personal experience:

```
Workspace
|_ durable_hello
    |_ __init__.py
    | function.json
|_ durable_hello_http_start
    |_ __init__.py
    | function.json
|_ durable_hello_orchestrator
    |_ __init__.py
    | function.json
|_ basic_hello
    |_ __init__.py
    | function.json
|_ basic_script
    |_ __init__.py
    | function.json
|_ shared
     |_ my_pack_one
         |_ __init__.py
         | class_one.py
     |_ my_pack_two
         |_ __init__.py
         | class_two.py
```

Then, you deploy this code to both your function apps (durable and basic). What you can do is you can use environment variables to disable certain functions on both function apps: if you set 'AzureWebJobs.durable_hello.Disabled = "true"' (also for `durable_hello_http_start` and `durable_hello_orchestrator`) then you only have the basic functions for this function app (and vice versa for the durable function app).

**Comment by ramya894** [comment]
@JeroenMBooij We are investigating the above issue and let you the findings soon.

**Comment by davidmrdavid** [comment]
In terms of folder structure and importing behavior: a Durable Functions app and an Azure Functions app should behave the same. This is because a Durable Functions app is just an Azure Functions app with an extra SDK :-) . So, to simplify the question, we should probably think of this as: if a user has two **separate** Azure Functions apps in one workspace, and wants to share code between them, how can they do this?

I believe @kummerer94 is correct in their assessment and recommendation. I don't think you can (or should) define shared code outside the root of a _given_ Functions app, and so it would be best to have it all under the same root, and selective disable Functions per deployment _if needed_.

And agreed that the new programming model should make this easier, though I can't comment on the specifics of the Durable integration of it just yet.

**Comment by ramya894** [comment]
Closing it as resolved.
