### ISSUE TITLE
[BUG] Improve Type Hints on Python Model V2

### ISSUE THREAD

**Issue by baluyotraf** [Azure/azure-functions-python-worker#1161]
Hello! We are playing around with the Python Model V2. We think it looks great, however the decorators fail when we apply our type checker (pyright on strict settings). Looks like the culprit is the type hint definitions on the decorators. The `Callable` type hint are not defined completely. For example:

```python
# https://github.com/Azure/azure-functions-python-library/blob/dev/azure/functions/decorators/function_app.py#L285

def function_name(self, name: str) -> Callable:
    ...
```

These can use the [recommendation from pyright][Pyright Decorators] or using the newer [ParamSpec] for typing.

I can work on this if needed since it's pretty simple yet pretty impactful for us.

[Pyright Decorators]: https://github.com/microsoft/pyright/blob/main/docs/type-stubs.md
[ParamSpec]: https://docs.python.org/3/library/typing.html#typing.ParamSpec

**Comment by bhagyshricompany** [comment]
Hi @baluyotraf  thanks for update will update you soon

**Comment by bhagyshricompany** [comment]
It sounds like you're encountering an issue where your type checker (pyright) is failing when applied to the decorators in the Azure Functions Python Library (azure-functions-python-library). The problem seems to be with the type hint definitions on the decorators, specifically the use of the Callable type hint. The Callable type hint is not defined completely, which is causing issues with your type checker.

One solution to this issue would be to update the type hint definitions on the decorators to be more specific. For example, instead of using Callable, you could use a more specific type hint such as Callable[[Arg1Type, Arg2Type], ReturnType]. This will give the type checker more information about the types of arguments and return values that the decorated function should have. Another way could be using new typing module introduced in python 3.10 called ParamSpec which is more specific, allowing more detailed function type hints.

Another solution would be to configuring your type checker to be less strict. This may allow it to process the decorators as they are currently defined, but it may also make it less effective at catching type-related errors in your code.

**Comment by baluyotraf** [comment]
Yes. It looks like we're on the same page on the problem.

AFAIK there's no way to override the `azure-functions-python-library` type definitions without copying the entire stubs in our repository. Maintaining the entire stubs of typing for the decorators seems a bit too much.

To allow the type checking to pass through our pipelines, we just put `# type: ignore` on every Azure functions decorator that we use in Python. While not ideal, we would like to keep the strict settings on our typings.

I guess on our side, we would like to know if there's a nicer workaround on the issue, or if there are plans to update the typing in the python library. For now we are fine to just get by with the `# type: ignore`.

**Comment by bhagyshricompany** [comment]
@vrdmr  please comment on this

**Comment by YunchuWang** [comment]
@baluyotraf Hi baluyotraf, i submitted an PR addressing this issue, can you please take a look and let me know if you have any questions

**Comment by YunchuWang** [comment]
pr merged, changes will go in next release in Feb

**Comment by baluyotraf** [comment]
Yup no complains here. Thanks!
