### ISSUE TITLE
Event Hubs Binding

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#119]
Add support for Event Hubs as a: 

- [ ] Trigger
- [ ] Output Binding

Goal is to enable the functionality and document the Python example here - [https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs)

For now, we can add the docs and samples to the [developer reference](https://pythondeveloperguide.azurewebsites.net/).

We will also need a template per this issue - https://github.com/Azure/azure-functions-templates/issues/646

**Comment by asavaritayal** [comment]
https://github.com/Azure/azure-webjobs-sdk-extensions
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventHubs

**Comment by elprans** [comment]
I am having trouble configuring the `eventHubTrigger` binding.  The documentation and the templates seem to differ from what's the EventHub extension currently expects.  The documentation specifies the "path" and the "connection" as the configuration for the binding, but the extension is failing to load with this:

```
fail: Host.General[0]
      The following 1 functions are in error:
      eventhub_trigger: Unable to configure binding 'event' of type 'eventHubTrigger'. This may indicate invalid function.json properties. Can't figure out which ctor to call.
```

Here's the relevant CI [log link](https://ci.appveyor.com/project/appsvc/azure-functions-python-worker/build/1.0.263#L440)

Having digged through the source, I found that it actually expects the binding to be configured using "eventHubName" instead of "path".  However, once I've set that to my event hub, I got this:

```
fail: Host.Startup[0]
      Error indexing method 'Functions.eventhub_trigger'
Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException: Error indexing method 'Functions.eventhub_trigger' ---> System.InvalidOperationException: No event hub receiver named python-worker-ci
   at Microsoft.Azure.WebJobs.ServiceBus.EventHubConfiguration.GetEventProcessorHost(String eventHubName, String consumerGroup) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.EventHubs\EventHubConfiguration.cs:line 290
```

See the PR #131 for the implementation details.

**Comment by pragnagopa** [comment]
Provided working C# sample in the PR

**Comment by AlverezYari** [comment]
This is marked close but I don't see any examples of the eventhub python bindings but its labeled as supported in the docs here: https://github.com/Azure/azure-functions-python-worker/wiki/Developer-Guide
