### ISSUE TITLE
Service Bus Binding

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#133]
Add support for Service Bus as a: 

- [ ] Trigger
- [ ] Output Binding

Goal is to enable the functionality and document the Python example here - [https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus)

For now, we can add the docs and samples to the [developer reference](https://pythondeveloperguide.azurewebsites.net/).

We will also need a template per this issue - https://github.com/Azure/azure-functions-templates/issues/646

**Comment by elprans** [comment]
It looks like the ServiceBus extension messes up the messages somehow.  Instead of sending the actual message body, the host sends literally `"System.Byte[]"`.  Moreover, other bindings get messed up as well, so even http returns `"System.Byte[]"` instead of the actual function output.

I'm using "Microsoft.Azure.WebJobs.ServiceBus" version "3.0.0-beta5"

\cc @pragnagopa

**Comment by pragnagopa** [comment]
Moving to next milestone. Will investigate

**Comment by pragnagopa** [comment]
Here is a sample function.json with javascript functions
[Node/ServiceBusQueueTriggerAndOutput](https://github.com/Azure/azure-functions-host/tree/dev/test/WebJobs.Script.Tests.Integration/TestScripts/Node/ServiceBusQueueTriggerAndOutput)
Can you give share function code? and the test code you using to invoke the function?

**Comment by asavaritayal** [comment]
Pending: 
- CI (App Veyor) resolution

**Comment by alexgman** [comment]
Can we do output bindings to a service bus queue from a python function?
