### ISSUE TITLE
Using blob triggers and blob output

### ISSUE THREAD

**Issue by dipesh747** [Azure/azure-functions-python-worker#1432]
I need dynamic directory paths for blob trigger. I also need dynamic directory names for blob output  names.

Example for trigger: 
Landing/{dir}/{name} 

If dir can be 1 through to 5 and name can be anything. 

How is this set in the decorator/where can I define possible values? 

For the output file name, where can I define that? 

I've read all the docs and I don't see this listed anywhere. Appreciate any help you can offer.

**Comment by hallvictoria** [comment]
Hello, this can best be accomplished using SDK type bindings.

If you want the blob trigger function to execute for any blob, you can set the path param to the top-level directory. The client can then be used to obtain the blob name. If you are interested in monitoring an entire container, the [ContainerClient](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.containerclient?view=azure-python) type might be more useful, otherwise the [BlobClient](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python) type will help.

```
@app.blob_trigger(arg_name="client",
                  path="container/directory",
                  connection="<connection_string>")
def blob_trigger(client: blob.BlobClient):
    # Get blob name from BlobClient
    blob_properties = client.get_blob_properties()
    file_name = blob_properties.name
```

For setting the output file name dynamically, this isn't supported with output bindings. However, the client type can be used to upload the blob. If you want to upload to a different container, you will need to use the SDK directly, though.
`client.upload_blob(<filename>, <data>), overwrite=True)`

Please see this documentation for more information:
- [Python Developer Reference - SDK Type Bindings](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=get-started%2Casgi%2Capplication-level&pivots=python-mode-decorators#sdk-type-bindings-preview)
- [SDK type bindings for Azure Blob Storage](https://techcommunity.microsoft.com/t5/azure-compute-blog/azure-functions-sdk-type-bindings-for-azure-blob-storage-with/ba-p/4146744)
- [azure-storage-blob SDK API Reference](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob?view=azure-python)
