### ISSUE TITLE
Add type checking for durable clients

### ISSUE THREAD

**Issue by gavin-aguiar** [Azure/azure-functions-python-worker#1515]

**Comment by davidmrdavid** [comment]
@vrmdr, @gavin-aguiar: I believe this requires Python worker special support, I recall we had talked about this when GA'ing support for DF in Python prog-model V2. This is because the worker thinks the durable client type is a string, but in reality DF is using that string to construct the object behind the scenes.

**Comment by davidmrdavid** [comment]
For that reason - should we not move this back to the Python worker repo, @vrdmr? It's not something the DF team can unblock by itself.

**Comment by gavin-aguiar** [comment]
@davidmrdavid Transferred it back.  It will be a change in the python library but we need to validate it with the worker.

**Comment by gavin-aguiar** [comment]
Fix is merged. [DurableClient Converter by hallvictoria · Pull Request #206 · Azure/azure-functions-python-library (github.com)](https://github.com/Azure/azure-functions-python-library/pull/206)
