### ISSUE TITLE
About how to reference the module

### ISSUE THREAD

**Issue by masamori0083** [Azure/azure-functions-python-worker#1576]
#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) 
general
#### Question
Hi, I always use Azure functions, thanks!
This might be bit question, I found this code in python-library directory. 

https://github.com/Azure/azure-functions-python-library/blob/2e5ea4fa04ddaea1d19872fe73b96f709e799268/azure/__init__.py#L4C1-L4C65

Currently this writing style is officially deprecated in python.
In particular, I think direct imports such as 
```
from pkgutil import extend_path
 __path__ = extend_path(__path__, __name__)
```
are more concise and easier to understand.   
Is there any reason why you have not written in this way?

Thanks

**Comment by hallvictoria** [comment]
Hi @masamori0083, thanks for reporting.

We used this import style to be consistent with other Azure SDKs (eg: [azure-storage-blob](https://github.com/Azure/azure-sdk-for-python/blob/86d97f651c7e5030f98aac00e753309323e48042/sdk/storage/azure-storage-blob/azure/__init__.py#L1)). Since it works as expected and isn't necessarily code that's exposed or that users directly interact with, we haven't seen a need to change it.

If this style is deprecated, we can look at refactoring it, but it wouldn't be a high priority item for the team right now.
