### ISSUE TITLE
Missing code for publishing functions to Azure Function App

### ISSUE THREAD

**Issue by cfloressuazo** [Azure/azure-functions-python-worker#199]
In this link: https://github.com/Azure/azure-functions-python-worker/wiki/Create-Function-(CLI), available in the README.me file, the title says "Build and publish using the Functions Core Tools", but in the link for the WIKI you only have the code up to running the function locally and not publishing it back to Azure.

I think the explanation needs to be added after the local testing and the code you should add is the following:
func azure functionapp publish <FunctionAppName>

or you can change the title to only "Build and local testing using the Functions Core Tools".

**Comment by asavaritayal** [comment]
Thank you for filing an issue about this. The instructions were pulled out temporarily since we discovered a regression in the tools. The wiki is now updated - 

- https://github.com/Azure/azure-functions-python-worker/wiki/Create-your-first-Python-function
- https://github.com/Azure/azure-functions-python-worker/wiki/Developer-Guide
