### ISSUE TITLE
Zip deploy from VS Code does not reflect all the Http Trigger URL's

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#209]
Created 2 HTTP Triggers:
CreateRating
GetProduct.

Deployed successfully through VS Code.

Created another 2 triggers:
GetRatings
GetRating.

Redeployed. It shows only the previous two in the logs, but in Azure all four are deployed successfully. Basically it doesn't reflect the zip deployment contents accurately. 

HTTP Trigger Urls:
  CreateRating: https://hogsmeade.azurewebsites.net/api/CreateRating
  GetProduct: https://hogsmeade.azurewebsites.net/api/GetProduct
2:36:14 PM Hogsmeade: Starting deployment...
2:36:15 PM Hogsmeade: Uploading zip package to storage container...
Deployment to "Hogsmeade" completed.
HTTP Trigger Urls:
  CreateRating: https://hogsmeade.azurewebsites.net/api/CreateRating
  GetProduct: https://hogsmeade.azurewebsites.net/api/GetProduct

**Comment by EricJizbaMSFT** [comment]
Looks like you were deploying to a Linux Consumption plan? We fixed an issue around that, but haven't released the fix yet. See https://github.com/Microsoft/vscode-azurefunctions/issues/657 for more info (The change was to sync triggers after deploying).

I'm not sure how the core tools handles deploying to linux consumption. Maybe they already sync the triggers? The linux consumption deployment through VS Code is kind of a "custom" implementation since that plan type doesn't support the 'zipdeploy' api (which normally syncs triggers for us).

**Comment by asavaritayal** [comment]
@EricJizbaMSFT got it - thanks for clarifying. Do you have an estimate for when the next release is going to be? So we can give it another try then.

**Comment by priyaananthasankar** [comment]
@asavaritayal  Haven't seen this with core tools.

**Comment by asavaritayal** [comment]
Got it, thanks.

**Comment by asavaritayal** [comment]
This issue was moved to Microsoft/vscode-azurefunctions#677
