### ISSUE TITLE
función en azure, no me muestra el lenguaje python. No permite instalar librerias en el servidor

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-python-worker#211]
_From @Dennis0095 on September 27, 2018 16:31_

Buen día, he creado una función en azure con javascript, ya que no me permite crearlo .
No me permite realizar solicitudes con el REQUEST. Luego, intento instalarlo, pero no se puede
porque no tengo permisos para acceder al servidor.""

Alguien que le haya pasado lo mismo,? Alguien saber si una cuenta free de esos ciertos liits+

_Copied from original issue: Azure/azure-functions-host#3530_

**Comment by pragnagopa** [comment]
Translated to english:

 function in azure, it does not show me the python language. It does not allow to install libraries on the server

Good day, I created a function in azure with javascript, since it does not allow me to create it.
It does not allow me to make requests with the REQUEST. Then, I try to install it, but you can not
because I do not have permission to access the server. "

Someone who has been the same ,? Someone know if a free account of those certain liits +

**Comment by pragnagopa** [comment]
@asavaritayal - Any ideas?

**Comment by priyaananthasankar** [comment]
Make sure you have the right function core tools. It happened to me as well (showed only C# and javascript) because my core tools library was pointing to an older one (older func core tools without python). Download latest azure func core tools in the instructions (which is in private preview) and it should show Python. Make sure when you type "func" its picking the right executable.

**Comment by asavaritayal** [comment]
Closing the issue due to inactivity from the creator. Please feel free to re-open the issue with information on how to reproduce the error.
