### ISSUE TITLE
No logs when 500 caused by issue preventing function from being loaded

### ISSUE THREAD

**Issue by brettcannon** [Azure/azure-functions-python-worker#261]
If you have something like an unhandled `ImportError` that occurs at load time of your function code, the user gets a 500 (which is correct), but there is no log produced anywhere for that 500. In my case I had to realize that trying to execute the function manually may show some traceback issue. But otherwise nothing shows up in the streaming logs, Application Insights, etc. to help debug this or even notify the user that the 500 is occurring.

**Comment by priyaananthasankar** [comment]
Yes the logging.info isnt showing up even when functions is run inside a container,

**Comment by elprans** [comment]
Errors like the `ImportError` are reported by the worker via `FunctionLoadResponse`:

https://github.com/Azure/azure-functions-python-worker/blob/e03026773f57145530224ab3a918e321a2c3efb9/azure/functions_worker/dispatcher.py#L334-L340

We can double the `FunctionLoadResponse` with a `logger.exception()` there if that makes sense.

**Comment by asavaritayal** [comment]
Needs to be tested on both Linux consumption and dedicated.

**Comment by maiqbal11** [comment]
The issue here is that we are not logging exceptions at the point where a function fails to load.  We log exceptions when the failed function is **invoked**. @brettsam is working on a fix that will allow logging to ApplicationInsights when these kinds of exception occur - currently the logger design has limitations that prevent this from happening.

**Comment by maiqbal11** [comment]
This issue was moved to Azure/azure-functions-host#3975
