### ISSUE TITLE
Publish python template fails on Ubuntu due to pkg_resources==0.0.0

### ISSUE THREAD

**Issue by mikespub** [Azure/azure-functions-python-worker#287]
https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python

On Ubuntu 18.04, when you follow the Python in Functions quickstart guide, the template generated contains a requirements.txt file with the following content:

```txt
azure-functions==1.0.0a5
azure-functions-worker==1.0.0a6
grpcio==1.14.2
grpcio-tools==1.14.2
pkg-resources==0.0.0  # this causes deployment to fail
protobuf==3.6.1
six==1.12.0
````
The invalid package pkg-resources==0.0.0 causes publish to Azure to fail:

```
(.env) mikespub@mikesvm2:~/azure-func/mikesfunc1$ func azure functionapp publish mikesfunc1
Getting site publishing info...
pip download -r /home/mikespub/azure-func/mikesfunc1/requirements.txt --dest /tmp/azureworkerwc4ty4j3

There was an error restoring dependencies.ERROR: ['pip', 'download', '-r', '/home/mikespub/azure-func/mikesfunc1/requirements.txt', '--dest', '/tmp/azureworkerwc4ty4j3'] failed with exit code 1
```
If you remove or comment out that line, publish succeeds...

Would it be possible to filter out that package before generating requirements.txt?

**Comment by maiqbal11** [comment]
@ankitkumarr, did we recently make a change to have the pkg-resources include? I don't recall that being there previously.

**Comment by ankitkumarr** [comment]
@maiqbal11, no, we aren't adding that. It's an Ubuntu bug.

Sources-
https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1635463
https://github.com/pypa/pip/issues/4022

Although a bit hacky, on the tooling side, we could filter out `pkg-resources` on Ubuntu after running `pip freeze`. But, maybe it's better if we reference the issue in our documentation and let users remove that manually. Ideally, it should be fixed in Ubuntu.

**Comment by maiqbal11** [comment]
Thanks Ankit! Agree that we should have this as part of our documentation rather than hacking to remove it when publishing. We can remove the guidance once the Ubuntu bug itself is fixed. @mikespub, the guidance right now would be to manually remove the include when publishing. You should be able to track the bug fix in the link that Ankit shared above.  

@asavaritayal, can we make a note in our docs for people using Ubuntu that they should remove `pkg-resources` before publishing?

**Comment by maiqbal11** [comment]
Closing as this is not an issue with Python worker.
