### ISSUE TITLE
Function Apps on Linux Consumption show WarmUp function

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-python-worker#310]
Currently if you publish your functions to a Linux Function App running on the Consumption Plan, an additional function called `WarmUp` starts to surface in the project. This is a **known issue** and we're currently working on the fix.

## Where does this function show up?

The WarmUp function can surface in two ways: 

1. Core Tools 
    example -
    ![image](https://user-images.githubusercontent.com/8435148/52100864-2fdb5d80-258e-11e9-9aca-803637f962fb.png)

2. Portal 
    example -
    ![image](https://user-images.githubusercontent.com/8435148/52101279-af1d6100-258f-11e9-98a6-6878643647ba.png)

## How does it impact my Function App? 

The `WarmUp` function **does not** impact the functionality of the rest of your app. It's a harmless addition to the project and is expected to return a 404 for JavaScript and Python based apps. 

**We'll update this thread once the fix is available.**

**Comment by mr3bn** [comment]
Happy to see this issue out, noticed late on Thursday 1/31 and had me scratching my head. I have a behavior potentially related to this issue that I also started around the time this issue was opened. 

**Description** A locally-developed Linux Consumption function app with 4 functions total -- 2 with EventHub triggers (`StreamingA` and `StreamingB`) and 2 with HTTP triggers (`HTTPA` and `HTTPB`) only publishes the two EventHub triggers, ignores the HTTP triggers, and creates the WarmUp arbitrarily. 

![image](https://user-images.githubusercontent.com/11140105/52213010-dc9e2f00-285b-11e9-9510-38cb6490f193.png)

**Versions**: This function app and the functions were created using the Azure Functions extension for VS code, but I have observed the same behavior using Core Tools in PowerShell.

 * Azure Functions extension: 0.13.1
 * Functions Core Tools: 2.4.317

**Action**: `func azure functionapp publish dsml-sbx-east-recommender`

**Expected behavior:** all four functions, `HTTPA`, `HTTB`, `StreamingA`, and `StreamingB`, are published to the function app.

**Observed behavior**: only the StreamingA and StreamingB functions are deployed to the function app, along with the `WarmUp` function. 

Output from core tools:
![image](https://user-images.githubusercontent.com/11140105/52215372-ea56b300-2861-11e9-8d5b-9a9f60e5fd44.png)


Function app in portal after publish:
![image](https://user-images.githubusercontent.com/11140105/52215287-bbd8d800-2861-11e9-8ae5-6e51befaeb96.png)

**Comment by kushalmangtani** [comment]
Quick question regarding Warm-up function here: 
Does the Warm-up function reduces the cold-start time of the function app OR impacts the performance of cold-start in any way? 

I was testing a python cloud-function with Linux Consumption plan, and observed the cold-start time significantly reduces when the warmup function is enabled vs disabled (Cold start: ~ 9 sec to 400 msec respectively)?

**Comment by asavaritayal** [comment]
Closing dupe in favor of - https://github.com/Azure/azure-functions-host/issues/4015
