### ISSUE TITLE
AttributeError in worker.py when running function locally

### ISSUE THREAD

**Issue by tinaj2505** [Azure/azure-functions-python-worker#318]
#### Investigative information
I am following the documentation [https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python?toc=%2Fpython%2Fazure%2FTOC.json](url) to create an azure function in python. Everything goes smoothly and breaks when I execute "func host start".

![image](https://user-images.githubusercontent.com/7771840/52460326-b61c1480-2b37-11e9-93c9-2621e8569da3.png)

I am not sure if this is a dependency issue or not, any help is appreciated.

**Comment by asavaritayal** [comment]
@tinaj2505 what version of the Core Tools are you using?

**Comment by tinaj2505** [comment]
@asavaritayal I tried it both on "2.2.103" and  "2.4.317" but  got same issue.

**Comment by maiqbal11** [comment]
Can you try `choco uninstall azure-functions-core-tools` and then `choco install azure-functions-core-tools`? Not likely, but might be due to some inconsistent state during installation. If `choco` installations do not work, you can also try `npm install -g azure-functions-core-tools` after uninstalling the `choco` version. Feel free to circle back with the results if these steps don't work.

**Comment by tinaj2505** [comment]
Interesting, now it's working when I reboot my computer after uninstall/install azure core tools in choco. Thank you!
