### ISSUE TITLE
AttributeError: module 'azure.functions_worker' has no attribute 'start'

### ISSUE THREAD

**Issue by Flexron** [Azure/azure-functions-python-worker#322]
Had the similar that is closed here #304 

I have published my Python Azur function using the Azure Functions Core Tools command **func azure functionapp publish app_name --build-native-deps**

But when I go to the function published I see the following error : 

 Error:
` Function (confluence_call) Error: Failed to start language worker process for: python. bash exited with code 255 [90] Failed to execute script worker,AttributeError: module 'azure.functions_worker' has no attribute 'start'.`

Here is my requirement.txt : 
azure-functions
azure-functions-worker
azure-storage-blob
grpcio==1.14.2
grpcio-tools==1.14.2
protobuf==3.6.1
six==1.12.0
pandas

**Comment by asavaritayal** [comment]
@Flexron what version of the Core Tools are you running?

**Comment by Flexron** [comment]
@asavaritayal I'm using 2.4.299  (I think it's the latest, I installed it last week).

For information, I re-published my function adding --no-bundler option and I didn't get this error.

**Comment by asavaritayal** [comment]
@Flexron yes, the default path is not expected to work for all packages due to PyInstaller limitations. Please continue to use `--no-bundler`. 

More info here - https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#publishing-to-azure

![image](https://user-images.githubusercontent.com/8435148/52668738-37253400-2ec9-11e9-9b9f-e4676b22ba2a.png)

An an FYI, we're working on removing the PyInstaller dependency completely in the future. 

/cc @ankitkumarr @fabiocav

**Comment by Flexron** [comment]
Hello,

Publish function using **func azure functionapp publish app_name --build-native-deps --no-bundler** was working perfectly.
I have updated my function and so I have tried to re-publish the function build but I got the same error again : 

Error : 

>  Function (confluence_call) Error: Failed to start language worker process for: python. bash exited with code 255 [93] Failed to execute script worker,AttributeError: module 'azure.functions_worker' has no attribute 'start'.

My requirement.txt didn't change.

The only difference with the previous error is 

Now :
> exited with code 255 [93]

Before : 
> exited with code 255 [90]
