### ISSUE TITLE
worker.py does not need compatibility fix anymore

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-python-worker#456]
Revert https://github.com/Azure/azure-functions-python-worker/commit/e03026773f57145530224ab3a918e321a2c3efb9 as with Pyinstaller gone, we shouldn't have to do this anymore. 

Removing this helps, because right now if import fails, `ImportError` is raised and caught by `worker.py` which then tries to import differently. This results in real errors getting transformed into a different error.

Example from https://github.com/Azure/azure-functions-core-tools/issues/1050, the actual error was -
```
  File "C:\Users\xxxx\Documents\pyfirst\.environment\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.
```
but the error surfaced to the users was - 
```
 AttributeError: module 'azure.functions_worker' has no attribute 'start_async'.
```

### __Fix__
Revert [this commit](https://github.com/Azure/azure-functions-python-worker/commit/e03026773f57145530224ab3a918e321a2c3efb9)

**Comment by maiqbal11** [comment]
Had a little more time to think about this and I'm seeing a potential issue with doing this and https://github.com/Azure/azure-functions-core-tools/pull/1377 together. Once we flip the user dependencies to now take precedence, and given that we used to include system requirements in the `requirements.txt`, anyone who has an earlier worker installed in their site packages or virtual environment will fail as being incompatible. This will also be true if they have an older worker in their `requirements.txt`. At this point, it might be just a small proportion of users since we haven't been including system dependencies with `requirements.txt` for some time/we made the incompatible worker change back in late 2018. Wanted to bring this up here so that we are _ok_ with going forward with these changes and don't have any surprises. 

\cc @asavaritayal @ankitkumarr

**Comment by ankitkumarr** [comment]
@maiqbal11, that's a valid point! Thanks for bringing it up.

Because we already had a breaking change with Pyinstaller gone, and we had to make sure users downloaded new core-tools and re-published, I would be inclined to say that it's ok to have this error with super old Python worker versions. We probably want users in that state to update anyway. 

On the other hand (as you mentioned), even if the user did update core-tools, but are using a function app that was created using an older CLI would need to manually update the version there. But I suppose we also fixed a lot of bug and want users to update anyway. And it makes sense to do it now, rather post GA. Thoughts?
