### ISSUE TITLE
Unable to load multiple pickle objects at once from a blob container in an azure function

### ISSUE THREAD

**Issue by praneethnooli** [Azure/azure-functions-python-worker#458]
I'm new to Azure and Azure functions. I'm trying to host a machine learning problem through Azure functions. In order to do that, I need to load around some 100 models in pickle format from 4 different blob containers in Azure function and then use the loaded models to predict a new file. Currently, I'm only able to refer to a single model in a container by following this example https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#triggers-and-inputs and am unable to find a way to loop through all the available models from a blob container. 

I'm also facing issues in loading a pickle model from blob with func.InputStream argument. 
From a local file system, I can load a pickle object using the following function -
`
    def load_model(filename):
    
        with open(filename, 'rb') as model_file:
            return pickle.load(model_file)
`
May I know the equivalent of the above-mentioned function in Azure functions with func.InputStream referring to the pickle object and also an efficient way to load a number of pickle objects from blob container

**Comment by jtlz2** [comment]
@praneethnooli From the docs, `func.InputSteam` is a file-like object with a `read()` method. So can't you just do something like (cf https://stackoverflow.com/a/55010315/1021819):

```
def load_model(blobin: func.InputStream):

    return pickle.loads(blobin.read())
```

(modulo encoding?) ?

**Comment by praneethnooli** [comment]
Thanks, @jtlz2 for your answer. The solution you have provided is working for 1 object. Can you suggest me an approach to pre-load all the machine learning models from the blob container such that the prediction should be instantaneous by not loading the models every time a new input comes?

**Comment by jtlz2** [comment]
@praneethnooli Apologies - missed the second part of your question. Apart from combining the models into a single blob (or pkl) every time and deserializing it, you can use the Blob Storage API to pull down the models via the Python SDK (see https://azure-storage.readthedocs.io, https://docs.microsoft.com/en-gb/azure/storage/blobs/storage-quickstart-blobs-python), starting with e.g.

```
    from azure.storage.blob import BlockBlobService
    block_blob_service = BlockBlobService(connection_string=os.environ[BLOB_ENV])
    block_blob_service.get_blob_to_path(container_name, local_file_name, full_path_to_file2)
```

You can probably download to memory directly, not sure. You don't have to fire the Function on a blobTrigger (unless you want to) - you are then free to use an httpTrigger, timerTrigger etc. How are you sending in the 'new input' - httpRequest or as a blob input?

AFAIK the models will die with the Function, so it's going to be expensive however you cut it (how big are they in MB? This will also eat into your RAM/money budget). In order to persist them you could I suppose try (I haven't) creating your own Docker image (RAM/money budget again) with them baked in already which would save on traffic and only cost in load-from-file on the first call.

The python SDKs seem to be the way forward (over the single-blob blobTrigger) for now and give access to Indexes/indices, blob metadata, search etc. as well as e.g. Cognitive Services. Using an index puts you into the search cost centre rather than the metadata access cost centre.

That's about the limit of my knowledge at this point.

Sorry for butting in BTW - I am not an expert or from MS/Azure - just an interested member of the community especially while python support is in Preview.. Do tag me if I can be of any further assistance or post a question on stackoverflow.

**Comment by praneethnooli** [comment]
Thanks, @jtlz2 again for your response and I really appreciate it for your assistance.  My overall combined model's size is around 3 GB and my new input will be a blob input. I think as you suggested in order to persist the models, a docker image needs to be created. Even I haven't created any docker image so far to persist the models. It would be great if someone who has already faced this issue of persisting the models can provide their solution if there is a better approach.

**Comment by balag0** [comment]
Pre-downloading the models should only be required once for each new instance of the app. It is true the cold start request will be impacted but subsequent requests should be able to load the models locally.
Will that work for your scenario ?

**Comment by elliotchaim** [comment]
@praneethnooli My team faced a very similar issue; the only difference being that we deployed my .pkl file with my code due to budgetary constraints. 

Our solution was to declare a global variable outside the scope of the httptriggered function. If the value is None then the function knows to initialize by ubpickling the model. 

The result is that the first request takes some time, with subsequent requests responding much much faster

**Comment by maiqbal11** [comment]
Closing this issue as stale. Please feel free to re-open if further assistance is needed.
