### ISSUE TITLE
Time issue: Exception: AttributeError: module 'azure.functions' has no attribute 'get_binding_registry'

### ISSUE THREAD

**Issue by docgregt** [Azure/azure-functions-python-worker#504]
Firstly, this code has been running for months. Secondly, the last time I deployed two days ago the deployment worked fine. Now today I deploy my function app that two timers in it and neither timer will work.
I get following errors:
Result: Failure
Exception: AttributeError: module 'azure.functions' has no attribute 'get_binding_registry'
Stack:   File "/usr/local/lib/python3.6/site-packages/azure/functions_worker/dispatcher.py", line 241, in _handle__function_load_request
    function_id, func, func_request.metadata)
  File "/usr/local/lib/python3.6/site-packages/azure/functions_worker/functions.py", line 194, in add_function
    param_bind_type, param_py_type)
  File "/usr/local/lib/python3.6/site-packages/azure/functions_worker/bindings/meta.py", line 36, in check_input_type_annotation
    binding = get_binding(binding)
  File "/usr/local/lib/python3.6/site-packages/azure/functions_worker/bindings/meta.py", line 20, in get_binding
    registry = get_binding_registry()
  File "/usr/local/lib/python3.6/site-packages/azure/functions_worker/bindings/meta.py", line 13, in get_binding_registry
    return func.get_binding_registry()

I tried rebuilding everything from scratch. Deleted my .env, etc. to no avail. Deleted the app service and recreated it. Nothing helps.

The timers work fine in Visual Studio Code running on my local machine.
Python 3.6.8
CLI 2.0.67
azure-functions==1.0.0a5
azure-functions-worker==1.0.0a6

I dont know what else to do. I would appreciate how to solve it.
Greg

**Comment by maiqbal11** [comment]
We've made changes to remove our dependencies from the `azure` namespace so that we no longer run into conflicts with user-included dependencies. The `azure-functions` package should be kept as part of the `requirements.txt` as it is a dependency needed for user code. We've made changes to our tooling to include `azure-functions` in new apps by default. `azure-functions-worker` should not be included in the `requirements.txt` as it is an implementation detail on our end. Thanks everyone for your patience with this as we iron out the experience while moving from preview to general availability!

**Comment by twentytwokhz** [comment]
Just wanted to point out this also happened to me when targeting an older azure-function version.
The current ones that are listed in the release history are:

_Sept 11, 2019_
`azure-functions==1.0.4`

_Sept 5, 2019_
`azure-functions-worker==1.0.0`
