### ISSUE TITLE
Python worker should report worker version in Kusto

### ISSUE THREAD

**Issue by Hazhzeng** [Azure/azure-functions-python-worker#512]
Querying with
```
FunctionsLogs
| where PreciseTimeStamp >= ago(1h)
| where RoleInstance contains {SOME_PYTHON_CONSUMPTION_INSTANCE}
| where Source contains "python"
```
The worker version column is missing.

**Comment by divyagandhii** [comment]
We don't need a separate worker version column for this. We can just add the version in the log entry when we start the language worker process, similar to how we do it for other languages. 

 FunctionsLogs
| where PreciseTimeStamp >= ago(30min)
| where Source contains "java"
| where Summary contains "[INFO] {Application.main}: Azure Functions Java Worker  version"

**Comment by kulkarnisonia16** [comment]
@Hazhzeng - can we do this as mentioned by @divyagandhii. This will be specially important once we have 3.7

**Comment by Hazhzeng** [comment]
@kulkarnisonia16 Yep, I think this is feasible. We can discuss this on weekly python sync.

**Comment by AnatoliB** [comment]
I want to do this for PowerShell worker as well. I have found, however, that the message for Java is formatted like this:
```
Azure Functions Java Worker  version [ 1.5.0]
```
(note the double space between `Worker` and `version` and a space after `[`). Because of this, I was having troubles finding anything with the Kusto query above. I thought this was just a typo, but then I found https://github.com/Azure/azure-functions-java-worker/pull/157, which intentionally (?) introduced these extra spaces.

@pragnagopa Is this to work around an issue with parsing this output somewhere? Is this still relevant and we should follow this pattern for all languages?

**Comment by pragnagopa** [comment]
@AnatoliB - thanks for pointing out the space issue. This was not intentional. As long as system log is appended with right prefix: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/LanguageWorkerConstants.cs#L40 host will treat it as system log and we can see logs in kusto

**Comment by maiqbal11** [comment]
Added in https://github.com/Azure/azure-functions-host/pull/5150
