### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.storage 'error

### ISSUE THREAD

**Issue by Viswa-Ranjan-Sahu** [Azure/azure-functions-python-worker#561]
#### Investigative information

Please provide the following:

- Timestamp:
- Function App name:
- Function name(s) (as appropriate):
- Core Tools version: 

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Links to source
* Contents of the requirements.txt file
* Bindings used

**Comment by Viswa-Ranjan-Sahu** [comment]
HI Anirudh , i have just setup the whole setup yesterday  so i assume the core tools  should be latest 
steps done:
1. got node.js
2. npm install -g azure-functions-core-tools
this is as of yesterday ,is there an update command or version which i should try to get.
I am pretty sure it ia Az Fn issue as , the normal python without the AZFn form works fine.

**Comment by Viswa-Ranjan-Sahu** [comment]
Quick Update 
i just tried to update AZFn core function tools using install or update core tools .But still the issue remains.

> azure-functions-core-tools@2.7.1704 postinstall C:\Users\vsahu003\AppData\Roaming\npm\node_modules\azure-functions-core-tools
> node lib/install.js

attempting to GET "https://functionscdn.azureedge.net/public/2.7.1704/Azure.Functions.Cli.win-x64.2.7.1704.zip"

+ azure-functions-core-tools@2.7.1704
updated 1 package in 10.44s
Finished running command: "npm install -g azure-functions-core-tools@2".
Running command: "npm install -g azure-functions-core-tools@2"...
C:\Users\vsahu003\AppData\Roaming\npm\azurefunctions -> C:\Users\vsahu003\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
C:\Users\vsahu003\AppData\Roaming\npm\azfun -> C:\Users\vsahu003\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js
C:\Users\vsahu003\AppData\Roaming\npm\func -> C:\Users\vsahu003\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\main.js

> azure-functions-core-tools@2.7.1704 postinstall C:\Users\vsahu003\AppData\Roaming\npm\node_modules\azure-functions-core-tools
> node lib/install.js

attempting to GET "https://functionscdn.azureedge.net/public/2.7.1704/Azure.Functions.Cli.win-x64.2.7.1704.zip"

+ azure-functions-core-tools@2.7.1704
updated 1 package in 9.832s
Finished running command: "npm install -g azure-functions-core-tools@2".

**Comment by anirudhgarg** [comment]
Core tools look correct. Did you do a pip install on the requirements.txt when *not* using venv ? If not, please try that first.

**Comment by Viswa-Ranjan-Sahu** [comment]
Tried that too and the exact same issue still exists.
steps: 

deactivated the  venev
deleted the whole venv folder
recreated the venv 
without activating, went to venev\scripts> pip install -r  path\requirements.txt 
post everything  started vscode and initiated the function and still  the same issue 

is it running on your side on local?  i am literally confounded

**Comment by maiqbal11** [comment]
@Viswa-Ranjan-Sahu, you are using the pip install from within the venv it seems. You would need to open run `python -m pip install -r requirements.txt` from with a non-venv directory.

**Comment by Viswa-Ranjan-Sahu** [comment]
Quick Update:
Thnx Maiqbal11 ,your trick worked and the function App started working locally.
However, Now i am thinking, isn't it that the whole purpose of having a  Virtualenv is defeated  if i have to restore all related packages in virtualenv as well as in global env. Also, what happens if my virtualenv has a lower version of packages (3.6) as compared to 3.7 in global  env?
steps:
1. open CMD in admin mode
2. pip install -r pathToRequirements.txt\requirements.txt    
3. start azFn in VScode and select the venv and  BOOM!!

**Comment by anirudhgarg** [comment]
Well you have to decide whether you want to use VirtualEnv or Global Env. By definition Virtual Environments are there in the first place so that you can have your own environment separate from the global environment. We have done the work that you dont actually need the VirtualEnv to do local debugging.

**Comment by mail2atulm** [comment]
> @Viswa-Ranjan-Sahu, you are using the pip install from within the venv it seems. You would need to run `python -m pip install -r requirements.txt` from with a non-venv directory.

This worked for me

**Comment by zaiquiri72** [comment]
@Viswa-Ranjan-Sahu I am experiencing the same issue as you reported.

Although the **pip -m**  approach suggested by @anirudhgarg and @mail2atulm seems to fix the issue in the short term, I'm not very comfortable with that solution.

One of the things I observed is that although my Azure function will not debug locally due to the unfound package issue, it runs perfectly when deployed to my function app in Azure.  The packages deployed to the Azure function app appear to be controlled by the virtual environment that's specific to the VSCode project (exactly as you would expect).

The root cause of the problem appears to be the fact that the local debugging environment and the deployed Azure environment (for the same code version) are not the same.  @anirudhgarg if you happen to read this, if that's indeed the case I can't underscore how serious this issue is, it means that we can't trust that things which run/debug successfully in our local environment will run successfully when deployed up to Azure (and vice-versa, we can't be assured that anything which fails locally won't actually work when deployed to Azure). It really undercuts the whole purpose of having a local test/debug environment in the first place.

Digging a little deeper to try to understand what's going on here, I noticed that when I'm inside VSCode working on my function application, the blue status bar at the bottom indicates that VSCode is using Python 3.8.2 64 bit, and that the virtual environment is '.venv", as expected.  If I run **python --version** in the VSCode terminal window, it reports as expected that the Python version is 3.8.2 64 bit.  Also, my command prompt in the terminal window correctly indicates that my virtual environment is set to .venv.

### However..

If I fire up "debug" or "run" from the IDE menu, or execute **func start** from the terminal window, I get the message:

**Found Python version 3.6.8 :: Anaconda, Inc. (python3.6)**

Which begs the question, why is **func start** out "looking" for a version of Python at all?

Shouldn't it be using the one that's specified by the virtual environment that's associated with the VSCode workspace, since that's the environment that _every other part of the IDE_ is using and/or referencing?

A little research proves that the version of Python that **func start** is finding on my machine is the default python version  when no virtual environment is activated, which means **func start** is either oblivious to, or is not not respecting, the virtual environment setting of the workspace at all.

I'm not sure if there's some setting in VSCode or elsewhere that's controlling this behavior.  If there is, maybe @anirudhgarg can give us some pointers on what it is and how to change it.

**Comment by anirudhgarg** [comment]
@zaiquiri72 - thanks for your question. Firstly I want to assure you that the actual function host and language worker bits that are running on your local box are exactly the same as the ones running in the cloud. The issues that people seem to be hitting are because of the use of virtual environments or different environments like Ananconda. Firstly in Azure Functions we do not support Ananconda. Second virtual environments exist to replace the global environments if that is indeed you want that - they are a pure local convenience. We are not using virtual environments in the cloud. The workaround that was given is the best as it installs the packages globally and that is also what is used in the cloud.

**Comment by themaxx75** [comment]
If we need to use a virtual environment, what is the process for it to work? I work on multiple projects with different versions of python and packages, and virtual environments are mandatory in my case. It seems to me that running `func start` is not using currently activated python. 
I would expect `python3 -m venv .venv` and `source .venv/bin/activate` and `pip install -r requirements.txt` and `func start` to work, but it fails when importing packages that are installed in the activated virtual env.
Thanks
