### ISSUE TITLE
Parallel execution

### ISSUE THREAD

**Issue by kutoga** [Azure/azure-functions-python-worker#583]
I use a Python Azure Function inside a container which does a (relatively) cost-expensive clustering on the given data. A single request requires about 5-10 seconds. My problem is that it seems the number of workers is fixed to **1**.

All requests are independent of each other (expect for that they use the same read-only model). Is it somehow possible to use multiple workers?

Thank you

Dummy code:
```python
# __init__.py

readonly_model = load_model() # this takes "much" time and the model is memory intensive; therefore this is only done once

def main(req: func.HttpRequest) -> func.HttpResponse:

    result = readonly_model.cluster_data(req.get_json()) # this takes much time, but every request could do this in parallel

    return result
```

**Comment by maiqbal11** [comment]
Instead of using multiple workers (docs for that [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#functions_worker_process_count)), I would suggest that you wrap the `readonly_model.cluster_data(req.get_json())` into an `async` call and then `await` it. This allows each call to be schedule concurrently on our event loop which should you give better performance. Note that this gives you concurrency, but not parallelism - you can achieve that latter with the worker process count noted above, but the limit on worker processes is 10, while there is not limit on the number of concurrent calls that can be scheduled.

**Comment by kutoga** [comment]
Unfortunately, concurrency without parallelism is not that helpful in my case, because it is CPU-bound. On the other side, `FUNCTIONS_WORKER_RUNTIME` was the right solution :)

Thank you!
