### ISSUE TITLE
Expose correlation details from host

### ISSUE THREAD

**Issue by yojagad** [Azure/azure-functions-python-worker#585]
Correlation details from host needs to be exposed as part of python function. This is already happening for node, java and powershell.

Bigger epic workitem: https://github.com/Azure/azure-functions-host/issues/3747
Related PR: https://github.com/Azure/azure-functions-python-worker/pull/554

**Comment by maiqbal11** [comment]
Before we can do this, we need to import the new protobuf into Python.

**Comment by Hazhzeng** [comment]
Check with Yogesh for the unit tests and check in the code.

**Comment by Hazhzeng** [comment]
https://github.com/Azure/azure-functions-python-worker/pull/545 merged in

**Comment by KimLClark** [comment]
Kim Clark, from Alaska Airlines here, we've been waiting on this fix for python since September 2019.  Did it actually get implemented?  This issue points back to #545 which seems to say the PR for that code was cancelled due to test failures.  Is it actually implemented in a released version?  If not is it still planned to be?

**Comment by anirudhgarg** [comment]
@KimLClark yes this is done  and deployed. Please let us know if its not working for you.
