### ISSUE TITLE
Library that requires another, both in requirements.txt for Python Function App

### ISSUE THREAD

**Issue by davidmosen** [Azure/azure-functions-python-worker#594]
Using the requirements.txt file to install the dependencies for a Python Function App can be limiting.

Say that one library (hawkeslib) requires another (Cython) to be installed first. If both are in the same requirements file, the installation of hawkeslib fails with ImportError: No module named 'Cython'.

The alternative is to use custom image to create Function Apps, but there has to be a middle ground in terms of flexibility, say allowing for additional prior commands to be executed on the remote environment, without having to resort to Docker.

**Comment by kulkarnisonia16** [comment]
@ankitkumarr - can you add documentation before closing this based on investigation?

**Comment by Hazhzeng** [comment]
This is an unusual scenario and the reason why a package requires Cython because the package you want to use is no longer supported in the current Python version and needs to be recompiled.

Currently, there are two blockers for performing multistage dependencies resolution in Python function app.
1. The dependency resolution service is provided by [Microsoft/Oryx](https://github.com/microsoft/Oryx/blob/master/doc/configuration.md#oryx-configuration) a limitation on our side which only supports a single requirements.txt file.
2. The Oryx Build does not take in installed Python Libraries for build process. Installing Cython on our build server doesn't mean you can use it right away.

Instead, one thing you can try out is by setting **PRE_BUILD_COMMAND** app settings in your function app to perform arbitrary build steps. [Docs Here](https://github.com/microsoft/Oryx/blob/master/doc/configuration.md#oryx-configuration). You can try uploading your build_script.sh and execute it in the pre build command.
