### ISSUE TITLE
Enqueued_time is None and cannot access system_properties or annotations of the payload with event hub trigger

### ISSUE THREAD

**Issue by richardleeaus** [Azure/azure-functions-python-worker#639]
When using Python Function v3 with EventHub trigger, there is no way to access the `system_properties` or `annotations` of the message.  This is when inspecting the returned event object. The `enqueued_time` is also **None**.

```python
import logging
import os
import json
import azure.functions as func

def main(event: func.EventHubEvent):
    logging.info('Python EventHub trigger processed an event: %s',
                 event.get_body().decode('utf-8'))
```

function.json is
```json
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "type": "eventHubTrigger",
      "name": "event",
      "direction": "in",
      "eventHubName": "testhub",
      "connection": "test1234567insight_RootManageSharedAccessKey_EVENTHUB",
      "cardinality": "one"
    }
  ]
}
```
For example, the message is arriving in a EventHub from IoT Central. The message arriving at EventHub is the below (example). This is confirmed when using the EventHub SDK to receive a payload.

```json
{
  "body":{
    "temp":67.96099945281145,
    "humid":58.51139305465015,
    "pm25":36.91162432340187
  },
  "annotations":{
    "iothub-connection-device-id":"<deviceId>",
    "iothub-connection-auth-method":"{\"scope\":\"hub\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}",
    "iothub-connection-auth-generation-id":"<generationId>",
    "iothub-enqueuedtime":1539381029965,
    "iothub-message-source":"Telemetry",
    "x-opt-sequence-number":25325,
    "x-opt-offset":"<offset>",
    "x-opt-enqueued-time":1539381030200
  },
  "sequenceNumber":25325,
  "enqueuedTimeUtc":"2018-10-12T21:50:30.200Z",
  "offset":"<offset>",
  "properties":{
    "content_type":"application/json",
    "content_encoding":"utf-8"
  }
}
```

How do we access this information?

**Comment by Hazhzeng** [comment]
Hi @richardleeaus,

Thanks for reporting this issue, let me take a look into this at the end of this week.

**Comment by Hazhzeng** [comment]
Hi @richardleeaus,

This issue has already been fixed in https://github.com/Azure/azure-functions-python-library/commit/31927c13ec59eac2e0229d7e4fec98c1b4047ce9 on February.

Unfortunately, due to the recent incident, we have a deployment freeze and Azure Functions Core Tools hasn't been released for 2 months https://www.npmjs.com/package/azure-functions-core-tools.

We will let you know once we get update on our tooling side.

**Comment by Hazhzeng** [comment]
Since azure-functions 1.3.0, a new .metadata field is now accessible from EventHub and ServiceBus trigger.
![image](https://user-images.githubusercontent.com/48038149/91102098-5b64e380-e61d-11ea-84b7-35dc2ea901d4.png)
```python
from typing import List

import logging

import azure.functions as func


def main(event: func.EventHubEvent):
    for key in event.metadata:
        logging.warn(f'event.metadata[{key}] = {event.metadata[key]}')

```
This field will pass the raw metadata from the EventHub/ServiceBus extensions. You may want to pin the Extension Bundle version before using it. [Code Example](https://github.com/Azure/azure-functions-python-worker/files/5120489/EventhubMetadataExample.zip)
