### ISSUE TITLE
[BUG] 502 Bad Gateway on Python Function call that in reality succeeds

### ISSUE THREAD

**Issue by vstrien** [Azure/azure-functions-python-worker#689]
###### Please provide the following:

- Timestamp: 6/9/2020, 7:45:36 AM (GMT +2)
- Function App name: data-ingest-apps
- Function name(s) (as appropriate): data-ingest-atinternet
- Core Tools version: azure-functions 1.2.1

### Repro steps

Issue GET request with the correct key and parameters: 
* fromyyyymmdd=20200608
* untilyyyymmdd=20200608

### Expected behavior

The function gets called, runs either succesfully or fails. If it fails, records are visible in the "invocation traces" or in Application Insights

### Actual behavior

The function returns failure, but in reality succeeds. A "502 - Bad Gateway" is returned, but according to Application Insights the function succeeded.

This morning (June 6th), it failed at 7:45:36 AM (GMT+2), after 2:36 min. of running (7:48:12 AM GMT +2). 
When retried (with the exact same parameters) at 8:18:15 AM (GMT +2), the function succeeded after 3:18 min. of running.

![retry-run](https://user-images.githubusercontent.com/91044/84117848-723e6580-aa32-11ea-9a1c-e74cac9cd043.png)

In Application Insights *requests*, the first run can be found, but it shows up as *succeeded* (although it returned a 502 Bad Gateway):

![appinsights](https://user-images.githubusercontent.com/91044/84117987-a580f480-aa32-11ea-91a3-244346c98a5d.png)

In the *traces* can be seen that there is interaction with ADLS which generates logging. The run ends at 5:47:46 UTC with returning a 200 OK:

![appinsights-traces](https://user-images.githubusercontent.com/91044/84131616-1204ef00-aa45-11ea-99ce-ff496a5323dd.png)

Around 30 seconds later the calling ADF pipeline receives a 502 Bad Gateway

###### Provide a description of any known workarounds.

Retrying after a while may result in a successful run.

###### Provide the requirements.txt file to help us find out module related issues.

```
azure-functions
requests
azure.core
azure.storage
azure.storage.blob
azure-storage-file-datalake>=12.0.1
gspread
oauth2client
pandas
analytics-data
pytz
postmarker
google-api-python-client
datetime
```

###### Provide any related information

* Links to source
* Bindings used

The last statement that is executed (according to the App Service Logs) is the following:

<details>
<summary>Source return statement</summary>

```python
    return func.HttpResponse(
        '{"success": "Uitvraag voltooid"}',
        status_code=200
    )
```
</details>

**Comment by vstrien** [comment]
Since I reported this 6 days ago, this has happened every single day.

For example 2020-06-10: failed four times, succeeded fifth time.

Called on (UTC +2)

* 2020-06-10 07:45:29 (ran 2:23 min.)
* 2020-06-10 08:18:01 (ran 3:14 min.)
* 2020-06-10 08:51:16 (ran 3:00 min.)
* 2020-06-10 09:24:18 (ran 3:06 min.)
* (finally succeeded 2020-06-10 9:57:24 AM, in 2:43 min.)

Inside Azure Functions Monitoring, only the **first run** (which returned a 502) is visible - and according to Functions it is **succeeded** (notice times are in UTC here)

![image](https://user-images.githubusercontent.com/91044/84626387-4b29dd00-aee5-11ea-8460-fa13eca194e2.png)

**Comment by balag0** [comment]
You are right it is not due to the Azure load balancer timeout limit of 230 seconds.
I noticed whenever the function invocation fails it is on an instance where there are multiple concurrent invocations going on. So I suspect these failures are due to the app hitting the consumption sku resource limit of 1.5 Gb memory.

The retries succeeding is due to that invocation being sent to a different worker instance.

Are these functions memory intensive? One recommendation is to split these functions into individual function apps instead of grouping all the functions in the same app. This would ensure each invocation goes to a distinct instance reducing the memory load.

This might not completely fix the problem since 2 invocations of the same function could still end up on same instance but this should help isolate the problem for futher investigation.

**Comment by vstrien** [comment]
Yes, it's certainly possible to split the functions into individual function apps. Also, I could have a second look at the batch size they're processing.

However, it still confuses me that the functions (according to `requests` in Application Insights) run successfully, whereas they return a 502 when being called.

Is there a way to see any logging where memory usage shows up as a problem?

**Comment by balag0** [comment]
Can you share one of those invocation ids that shows up as success in requests table but actually failed. You can get the invocation id from the customDimensions column in requests table.

**Comment by vstrien** [comment]
Sure, here is an invocation from the original post: 

* f9b07633-3d87-4885-9b42-535640b16379

Here is a more recent one:

* 2266c616-ad75-445c-af49-607be0b7197e

**Comment by asears** [comment]
Any updates on this bug?  Documentation still shows that this is a load-balancer limitation, is this correct assumption?

I see this issue for for missing handling of SIGKILL on a python out-of-memory condition, not retrying or scaling out the request.  
https://github.com/Azure/azure-functions-python-worker/issues/578 

In most cases the long-running, high-memory http requests we are using succeed, though 502 gateway is returned to the caller and logged.  It would be nice if it just churned away (as it does locally) rather than failing out in the worker or on the host.

Have tried scaling to P3V2 instance, same effect.  It could be outdated host?

In our case, we would like to suppress the error and to understand scale options for high-memory, high-cpu, long running, retryable python functions.

**Comment by arroyc** [comment]
closing this issue as it seems to be inactive, please feel free to create a new issue and refer this issue if you still facing the problem
