### ISSUE TITLE
[BUG] Logging level debug does not work in local or portal logs

### ISSUE THREAD

**Issue by ijoosong** [Azure/azure-functions-python-worker#735]
###### Please provide the following:

In any python function, log level debug does not display in both local and portal logs.

###### Provide any related information

* Links to source
* Bindings used

**Comment by ijoosong** [comment]
![](https://dev.azure.com/azuretracking/71ad29ed-b999-4d82-b883-f094fc0894b3/_apis/wit/attachments/3ff268cf-ad19-4b25-836f-dd9f84d61e4d?fileName=image.png)

![](https://dev.azure.com/azuretracking/71ad29ed-b999-4d82-b883-f094fc0894b3/_apis/wit/attachments/c857db0c-464a-449e-af01-1d70f0e62aa5?fileName=image.png)

**Comment by ijoosong** [comment]
![image](https://user-images.githubusercontent.com/6217333/90199361-5e441680-dd89-11ea-8867-35849a3af443.png)

**Comment by Hazhzeng** [comment]
Just synced with my team offline @vrmdr and @stefanushinardi 

The `debug` level log was controlled by the azure-functions-host `--log-level` flag. https://github.com/Azure/azure-functions-python-worker/blob/dev/azure_functions_worker/main.py#L21

I think the `debug` level was reserved for the python worker log in old days. We're currently following up the function-host team to ensure if the `debug` level is no longer used.

Thanks for reporting this issue.

**Comment by pragnagopa** [comment]
@ijoosong - can you please share you `host.json`

Default log level is set to `information` for anything else you need to update `host.json` with the `loglevel`. For debug, your `host.json` should look like this:

```json
{
	"version": "2.0",
	"logging": {
		"LogLevel": {
			"Default": "Debug"
		}
	},
	"extensionBundle": {
		"id": "Microsoft.Azure.Functions.ExtensionBundle",
		"version": "[1.*, 2.0.0)"
	}
}
```

**Comment by anthonychu** [comment]
I was investigating this with @ijoosong a while back. Changing host.json doesn’t make a difference In this case because the worker currently hardcodes function logs to INFO as @vrdmr discovered.

**Comment by ijoosong** [comment]
@pragnagopa I've tried this and it doesn't work :(

**Comment by vrdmr** [comment]
@ijoosong We've figured out the fix and I'll send out the fix post-testing.

**Comment by Hazhzeng** [comment]
Thanks @pragnagopa, @vrdmr and @stefanushinardi for the offline sync up.
We determine that there're two places blocking the logging from emitting debug level logs:
1. When the worker process is created, the host is not passing `--log-level` flag into the argument, thus the Python worker will only emit the `INFO` log into console. https://github.com/Azure/azure-functions-python-worker/blob/dev/azure_functions_worker/main.py#L21
2. After the worker establishes GRPC channel to the host, the root logger will stop using console log and switch to GRPC log which is pinned to `INFO` https://github.com/Azure/azure-functions-python-worker/blob/dev/azure_functions_worker/dispatcher.py#L125

Since the GRPC logging handler is attached onto the root logger, currently we have a concern on the performance when dropping the `INFO` level constrain, since some third-party libraries are using `DEBUG` level logs (e.g. azure-storage-blob https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/policies.py#L201-L203).

**Comment by vrdmr** [comment]
@Hazhzeng 

> When the worker process is created, the host is not passing --log-level flag into the argument, thus the Python worker will only emit the INFO log into console. https://github.com/Azure/azure-functions-python-worker/blob/dev/azure_functions_worker/main.py#L21

How do we configure debug logging for workers logs from the host side? Is there an app setting that the host can pass in?

**Comment by Hazhzeng** [comment]
@vrdmr The host redirect all stdout and stderr from the Python process into their logging infra. They don't control logging level in Python worker, they're just filtering the worker logs.

**Comment by ijoosong** [comment]
Awesome thanks @vrdmr when will this change go live?

**Comment by vrdmr** [comment]
We are planning to get the new releases of the Python worker to go out by next week, I'll update you once that is done.

**Comment by YunchuWang** [comment]
@ijoosong it is released in function runtime v4 right now. Please refer to https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#python_enable_debug_logging for more details how to turn on user function debug logging.
