### ISSUE TITLE
PyCharm Integration? 

### ISSUE THREAD

**Issue by stefanushinardi** [Azure/azure-functions-python-worker#843]
Looking to get some data if users want PyCharm integration(mainly authoring, debugging, and publishing) for Functions Apps. Please thumbs up or comment in this thread to let us know what your thoughts on this. 

Thanks!

**Comment by agpt8** [comment]
I was already using functions with PyCharm, though all I could do was to run and stop the functions through command line. As an initial integration, authoring, debugging and publishing is really nice to have, but I would also expect adding/removing bindings, managing local/remote application settings, streaming logs and managing deployments (on at least some level). 

I do not expect feature parity with vs code but all of the above mentioned would make the experience a lot better if not better than vs code. 

Since debugging is already planned as an initial offering, I am really looking forward to this being implemented soon!

**Comment by SashiDareddy** [comment]
Yes - please. I use PyCharm for development and only have to switch to VSCode for the Azure function development. I would just prefer to have one IDE I can work end to end.

**Comment by wolfgangas** [comment]
Yes, please go ahead :) My team works with PyCharm for many projects and despite the inconvenient way of debugging we write our Azure functions with PyCharm and do not want to switch to VS Code

**Comment by agpt8** [comment]
Is there any update on this? Will this be pursued? If yes, do you guys have a roadmap or something for PyCharm support?

**Comment by vrdmr** [comment]
Thanks, @agpt8, @wolfgangas, @SashiDareddy for your input. We have to build a working prototype and iron bugs out. We'll keep you updated.

Closing this issue and creating a discussion for PyCharm usage and inputs and better handling of feedback: Please go to - https://github.com/Azure/azure-functions-python-worker/discussions/970

/cc @shreyabatra4
